### ISSUE TITLE
Device not ready errors when attempting to resolve path for bindings file

### ISSUE THREAD

**Issue by dexdexdex** [TooTallNate/node-bindings#28] opened 2016-10-27 03:30 UTC
I've been debugging a bunch of build failures that seem to stem from virtual machines in my build environment (physical machines seem to be fine). This is super weird.

It looks like all the builds fail when we try to run this line in our tests, bindings.js line 76:

`b = opts.path ? require.resolve(n) : require(n)
`

I've boiled it down to something even simpler:

`b = require("C:\\odbc_node.js");
`

We see a lot of "Error: The device is not ready"

The odbc_node.js file we get by extracting this: https://github.com/ibmdb/node-ibm_db/blob/master/build.zip

Any ideas?

**Comment by dexdexdex** [comment] 2016-10-27 03:31
I'm not sure our bug is actually in bindings.js. We can kind of reproduce it by reducing it down to this case:

```
var a = require("C:\\odbc_bindings.node");
console.log("HI");
console.log(a);
```

This also produces the 'device not ready' error on some machines but not others.

**Comment by TooTallNate** [comment] 2017-07-24 22:35
Ya, not a bug in node-bindings. Closing.

**Closed by TooTallNate** 2017-07-24 22:35 UTC
