### ISSUE TITLE
getFileName does not work in electron

### ISSUE THREAD

**Issue by xianjimli** [TooTallNate/node-bindings#29] opened 2017-01-08 03:11 UTC
getFileName does not work in electron,   In Electron, filename starts with "file://", it should be removed, or bind will failed.

```
exports.getFileName = function getFileName (calling_file) {
  var origPST = Error.prepareStackTrace
    , origSTL = Error.stackTraceLimit
    , dummy = {}
    , fileName

  Error.stackTraceLimit = 10

  Error.prepareStackTrace = function (e, st) {
    for (var i=0, l=st.length; i<l; i++) {
      fileName = st[i].getFileName()
      if (fileName !== __filename) {
        if (calling_file) {
            if (fileName !== calling_file) {
              return
            }
        } else {
          return
        }
      }
    }
  }

  // run the 'prepareStackTrace' function above
  Error.captureStackTrace(dummy)
  dummy.stack

 // cleanup
  Error.prepareStackTrace = origPST
  Error.stackTraceLimit = origSTL

  //In Electron, filename starts with "file://"
  var fileSchema = "file://";
  if(fileName.indexOf(fileSchema) === 0) {
     fileName = fileName.substr(fileSchema.length);
     //on windows
     if(fileName.indexOf(":/") == 2){
         fileName = fileName.substr(1);
     }
  }

  return fileName
}
```

**Comment by perymimon** [comment] 2018-12-12 19:51
i still reproduce it when i use `leveldown` package

**Comment by E3V3A** [comment] 2019-01-23 08:32
It seem that @TooTallNate is too concerned telling people about his height. :thinking:  A PR has fixed the issue but has not been merged...

**Closed** 2019-01-23 21:08 UTC

**Comment by thisTom** [comment] 2019-08-27 06:31
> hi I have the same problem，This code returns undefined，In nw.js version 0.14.7 , use ffi
> `Error.prepareStackTrace = function (e, st) { for (var i=0, l=st.length; i<l; i++) { fileName = st[i].getFileName() if (fileName !== __filename) { if (calling_file) { if (fileName !== calling_file) { return } } else { return } } } }`

i have the same problem ,when i use electron and ffi

**Comment by pjebs** [comment] 2020-04-16 06:50
This issue is still not fixed for electron  -- at least when `bindings` package is bundled using rollup. 

```
/**
 * Gets the filename of the JavaScript file that invokes this function.
 * Used to help find the root directory of a module.
 * Optionally accepts an filename argument to skip when searching for the invoking filename
 */
```

When bundled, it's already embedded _in_ the javascript. There is no other file that calls it.

This is the error:
```
Uncaught Exception:
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (/xxx/my-app/out/theCucumber.app.x/the-great-app-darwin-x64/the-great-app.app/Contents/Resources/app/src/bundle.js:260:16)
    at bindings (/xxx/my-app/out/theCucumber.app.x/the-great-app-darwin-x64/the-great-app.app/Contents/Resources/app/src/bundle.js:165:48)
    at Object.<anonymous> (/xxx/my-app/out/theCucumber.app.x/the-great-app-darwin-x64/the-great-app.app/Contents/Resources/app/src/bundle.js:1290:16)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5785:12)
```

This is the location of error:

```
  // handle filename that starts with "file://"
  var fileSchema = 'file://';
  if (fileName.indexOf(fileSchema) === 0) {
    fileName = fileUriToPath_1(fileName);
  }
```

**Comment by pjebs** [comment] 2020-04-16 06:51
Is it not standard practice to bundle your javascript files into 1 in electron?

**Comment by petertorelli** [comment] 2020-10-17 03:56
This is still bugged under electron and, for example: `npm usb`. Digging into `bindings.js`, if the variable `calling_file` is undefined (as it is when `opt.module_root` is undefined), the `prepareStackTrace` function exits before checking all of the possible locations in the call stack, which causes an `indexOf` on the undefined `fileName` variable a few lines later. If you comment out the return when `callsite` is undefined, it proceeds to look at all of the stack callsites. However, when running bindings on electron and `usb`, none of the callsite file paths contain the node bindings, because the bindings are under `./node_modules/usb/build/Release/usb_bindings.node`. Clearly nothing is invoked from `node_modules` in the stack at this point. I believe this might be related to search path for native modules? I'm not sure how to properly use bindings: how could I modify the `usb` package to put `usb_bindings.node` into one of the places searched?
